site_name: Documentacion del "AC-JHES"
theme:
  name: material
  favicon: images/avion.png
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  


nav:
  - Bienvenida: index.md
  - Manual de uso: user_manual.md
  - Desarrollo del proyecto: development.md
  - Manual de mantenimiento: mantaince_manual.md
  - Acerca de: 
    - ¿Qué es la cabina?: about/#que-es-la-cabina-de-simulacion-ac-jhes
    - Como contribuir: about/#como-contribuir
    - Contacto: about/#contacto
    - Licencia: about/#licencia
  